files:
  - source: /localization/sample(source).xml
    translation: /localization/%locale%_%original_file_name%
    "update_option" : "update_as_unapproved"
    translation_replace: {
    "en-Dk_" : ""
}
